### ISSUE TITLE
Installation Problem - Use of deprecated astropy API

### ISSUE THREAD

**Issue by AKuederle** [Aminsinichi/wearable-hrv#1]
Using pip install to install the package in a clean env results in errors during import.

Specficially, `ImportError: cannot import name 'LombScargle' from 'astropy.stats'`. This is likely related to the deprecation mentioned here (https://github.com/lightkurve/lightkurve/issues/535)

It seems like the package does not support recent astropy versions. That should be specified in the setup.py to ensure that compatible versions are installed (or even better, the newer versions of astropy should be supported).

Downgrading astropy to <6.0 fixed the issue for now

**Comment by Aminsinichi** [comment]
Thank you very much! Addressed the issue in setup.py by defining `atropy<6.0`. 
[Related commit]( https://github.com/Aminsinichi/wearable-hrv/commit/09ab91475e91172ebff59f0ef32b6ee9da71de84).
