### ISSUE TITLE
Joss Paper: Comparison to "state-of-the-art" and references for the process

### ISSUE THREAD

**Issue by AKuederle** [Aminsinichi/wearable-hrv#10]
While reading through the paper, I was missing a little bit more thoprough comparison to other available packages to clearer highlight what this package adds. E.g. how much easier is using this package than using the `hrv-analysis` package directly.

Also It would be great, if you could add citations to the paper that provide support for the evaluation metrics that the package provides. Basically, to provide some justification why you chose the set of metrics and plots that are included in the package for comparison of the systems.

**Comment by Aminsinichi** [comment]
Thank you! I added a paragraph and situated the package among the current existing packages to demonstrate its added value. Additionally, I included a few classic references on papers about using validation methods and their interpretations, which are also utilized in the `wearablehrv` package.

I also made changes and additions to ensure it remains updated with the latest updates of the package.
