### ISSUE TITLE
Some comments about Packaging and Versioning

### ISSUE THREAD

**Issue by AKuederle** [Aminsinichi/wearable-hrv#4]
Great job publisheing the package on Pypi!

Here a couple of suggestions to further improve packaging and distribution:

- [x] Your package should have an internal version identifier (usually a __version__ const in the init) that corresponds to the package version, so that users can check which version they have installed
- [x] You should associate each Pypi release with a git tag (and push the tag to Github) to make sure that people can browse the code of exactly the version they are currently running (e.g. when reporting bugs)
- [x] Optionally, you can create a Github release for every version
- [x] Optionally, you can streamline the process, by using Github actions to automatically publish on release or on tag
- [x] You should consider adding a changelog. Otherwise, new versions and their impact are meaningless to users.

**Comment by Aminsinichi** [comment]
- [x] The first suggestion was about including the __version__ to __init__. Apologies, I accidentally turned this into a new issue and then removed it. Your suggestion has been incorporated [related commit](https://github.com/Aminsinichi/wearable-hrv/commit/c19c010a71203a9a89820452f28785944ca1d455). 
- [X] Many thanks for these useful suggestions. I have now added a GitHub Action, which automates the process of publishing on PyPI, and is triggered by pushing the version as a tag, which hopefully will resolve the issue. [Related commit1](https://github.com/Aminsinichi/wearable-hrv/commit/bbce77ff86ff8b622d0b46ab991d832464e0cfdd); [Related commit2](https://github.com/Aminsinichi/wearable-hrv/commit/7340e3ba58fd2724931bb868a9a080839c9c6694)
- [X] Added a template changelog, and will update this with every newer version from now on [Related commit](https://github.com/Aminsinichi/wearable-hrv/commit/81af4cc227cba0ab2e4aeaa79ae72c3d5f513d1b).
