### ISSUE TITLE
Tests rely on hardcoded path

### ISSUE THREAD

**Issue by AKuederle** [Aminsinichi/wearable-hrv#5]
At the moment the testfiles try to add hardcoed paths to the sys.path

https://github.com/Aminsinichi/wearable-hrv/blob/ac22c3784c3952a67536c9c976a755827c136dc5/tests/test_group/test_group.py#L3

https://github.com/Aminsinichi/wearable-hrv/blob/ac22c3784c3952a67536c9c976a755827c136dc5/tests/test_individual/test_individual.py#L2

That should be adapted to make it possible to run the tests on every system without modifieing the files

**Comment by Aminsinichi** [comment]
Currently the path is dynamically determined based on `path = os.path.dirname(os.path.abspath(__file__))`. Additionally, a few more tests have been added based on the newly added core features. [Related commit](https://github.com/Aminsinichi/wearable-hrv/commit/f75f3f24abfe6510936bd8d33f1f11f47a0f03aa)
