### ISSUE TITLE
Package is missing contribution Guidelines 

### ISSUE THREAD

**Issue by AKuederle** [Aminsinichi/wearable-hrv#9]
As per JOSS requirements a package should have Contribution Guidelines:

Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by Aminsinichi** [comment]
Added! [here](https://github.com/Aminsinichi/wearable-hrv/blob/master/CONTRIBUTING.md).
